-- lgtm.nvim — review the diff of your branch's PR without leaving the editor.
--
--   :LgtmEdit [base]
--
-- Opens a tab with three panes: a tree of every changed file, the file as it
-- exists on the PR's target branch, and the live editable working-tree file.

local explain = require("lgtm.explain")
local git = require("lgtm.git")
local layout = require("lgtm.layout")
local markdown = require("lgtm.markdown")
local ruler = require("lgtm.ruler")
local state = require("lgtm.state")
local tree = require("lgtm.tree")

local M = {}

local defaults = {
    -- Base branch to fall back on when there is no PR and origin/HEAD is unset.
    base_branch = nil,
    -- Wider than a plain file explorer: rows carry +/- counts and status tags
    -- alongside deeply-nested paths.
    tree_width = 60,
    -- Fraction of the left column given to the PR description; the tree takes
    -- the rest.
    desc_height = 0.45,
    -- Fixed width for the read-only base pane; the working pane takes whatever
    -- is left. Set to nil to split the remainder evenly instead.
    base_width = 104,
    -- Use a single global statusline for the duration of the session. With
    -- per-window statuslines the description/tree split draws a status bar
    -- across the middle of the layout. Restored when the session closes.
    global_statusline = true,
    include_untracked = true,
    -- Where <End> goes after ticking a file: the next file, the next file you
    -- have not yet reviewed, or nowhere.
    advance = "next", -- "next" | "next_unviewed" | "none"
    -- Files marked -diff or linguist-generated in .gitattributes. GitHub
    -- collapses these; "skip" pre-ticks them so they stay out of your way while
    -- remaining visible and reviewable.
    generated = "skip", -- "skip" | "show"
    max_file_size = 1024 * 1024,
    gh_timeout = 8000,
    -- A strip down the right edge of the working pane showing where the hunks
    -- sit in the file as a whole, and which part of it you are looking at.
    ruler = true,
    -- The explanation column: a fourth pane, right of the working file, with one
    -- block per hunk, generated by a headless agent that is shown the PR and this
    -- file's diff and can read the rest of the repository. Toggled, never opened
    -- with the session — it costs a model call per file, and plenty of reviews do
    -- not want one.
    explain = {
        width = 76,
        -- One invocation for the whole PR, not one per file: a hunk is often only
        -- explicable by what moved in another file, and per-file re-sent the
        -- description and the stat every time while re-exploring the same shared
        -- code. Results still arrive a file at a time, because the agent writes them
        -- into a directory this watches.
        cmd = { "claude" },
        model = "sonnet",
        -- `Write` is here because the results *are* writes. It cannot be scoped to a
        -- directory through this list — every parenthesised form of Write is refused
        -- and bare Write is unscoped — so `ai.lua` passes a --settings deny rule for
        -- the repository instead, which is verified to hold. The working tree has
        -- your unsaved edits in it; the agent cannot touch it.
        tools = {
            "Read",
            "Grep",
            "Glob",
            "Write",
            "Bash(git diff:*)",
            "Bash(git log:*)",
            "Bash(git show:*)",
            -- `git blame` is deliberately absent. Its entire output is which commit
            -- last touched a line, and that is exactly what an explanation must never
            -- be about: the unit of review is the branch's cumulative diff, not its
            -- commits. Left available, it is what an agent reaches for when a diff
            -- looks too plain to be worth a sentence, and the result is a paragraph
            -- about a revision pointer instead of the table being created.
        },
        extra_args = {},
        -- A whole change, explored rather than skimmed. This is the ceiling on the
        -- run, not on the first file, which lands long before it.
        timeout = 1800000,
        -- How long to hold the run waiting for `gh pr view` to answer, so the agent
        -- is given the PR description rather than told there isn't one.
        pr_wait = 3000,
        -- Reserve blank display rows below a region when its explanation is
        -- taller than the rows the diff leaves beside it, so the prose is never
        -- squeezed into a gap that a closed fold has collapsed to one line. Blank
        -- virtual lines in both code panes; the file itself is not touched.
        pad = true,
        -- Cap on the one diff pasted into the prompt (the file you have open).
        max_diff_bytes = 60000,
    },
    -- Diff pane colours. Vim paints changed lines edge to edge, so the stock
    -- colours read as bars rather than highlighting; these blend the theme's own
    -- diff hues down to a wash and let DiffText carry the detail. Set to false
    -- to keep the colourscheme's styling untouched.
    diff_colors = {
        -- Only the hue of these is used; saturation and lightness are rebuilt
        -- against the background. Cyan rather than green for additions: red/green
        -- is the pair that red-green colour blindness collapses. Pass "theme" to
        -- derive the hue from the colourscheme instead.
        -- hue in degrees; line_l/word_l are lightness offsets from the
        -- background. Negative means darker than the background, which is what
        -- keeps the tint behind the code rather than on top of it.
        add = { hue = 223, sat = 0.97, line_l = -0.039, word_l = 0.030 },
        delete = { hue = 0, sat = 0.97, line_l = -0.037, word_l = 0.021 },
        -- Filler rows. hue/sat default to the background's own, so they read as
        -- the page a shade paler rather than as a foreign grey; only the
        -- lightness offset is set here. Lighter rather than darker, because a
        -- filler carries no text and is visible only by its contrast.
        filler = { l = 0.05 },
        -- Fold summary lines: quiet background, foreground lifted clear of it so
        -- the text is actually readable.
        fold = { bg_l = 0.035, fg_l = 0.30 },
        -- The textwidth guide, as a hint rather than a stripe.
        colorcolumn = { l = 0.022 },
        -- Inline `code` in a PR description: a chip plus a tinted foreground.
        -- hue defaults to the background's own so the chip blends; fg_* build
        -- the text colour. Fenced blocks reuse the chip, filled to the window
        -- edge, and carry no foreground of their own.
        -- Darker than the page rather than lighter, matching how the diff tints
        -- sit behind the code instead of on top of it, and on the same 223 hue
        -- as additions so the tool reads as one palette.
        code = { hue = 223, l = -0.03, sat = 0.28, fg_hue = 193, fg_sat = 0.42, fg_l = 0.50 },
        -- Colourschemes that let the terminal background show through (nord does)
        -- leave Normal's background unset, so there is nothing to measure and
        -- every tint here would be positioned against a guess. Set this to your
        -- terminal's background if the tints look too light or too dark.
        background = nil,
    },
    keys = {
        next_file = "<PageDown>",
        prev_file = "<PageUp>",
        next_file_alt = "]f",
        prev_file_alt = "[f",
        toggle_viewed = "<End>",
        toggle_explain = "<leader>ge",
        tree_toggle_viewed = "m",
        tree_open = "<CR>",
        tree_fold = "za",
        close = "<leader>gD",
        tree_close = "q",
    },
}

M.config = vim.deepcopy(defaults)

--- The one live session, or nil.
local session = nil

--- Forward declaration: the explanation pane is toggled from a function defined
--- above apply_keys, and its buffer needs the session's maps like any other.
local apply_keys

local function notify(msg, level)
    vim.notify("lgtm: " .. msg, level or vim.log.levels.INFO)
end

local function session_valid()
    return session ~= nil and session.tab and vim.api.nvim_tabpage_is_valid(session.tab)
end

--- The stream picker's rows: each guide stream priced against the actual change,
--- so the picker carries real counts rather than whatever the agent said. Paths
--- the guide names that are not in the change are simply not counted.
local function feature_rows()
    if not (session and session.guide) then
        return nil
    end
    local by_path = {}
    for _, e in ipairs(session.all_entries or session.entries) do
        by_path[e.path] = e
    end
    local rows = {}
    for _, f in ipairs(session.guide.features or {}) do
        local n, added, deleted, viewed = 0, 0, 0, 0
        for _, p in ipairs(f.files or {}) do
            local e = by_path[p]
            if e then
                n = n + 1
                added = added + (e.added or 0)
                deleted = deleted + (e.deleted or 0)
                if session.store:is_viewed(p) then
                    viewed = viewed + 1
                end
            end
        end
        table.insert(rows, { title = f.title, files = n, added = added, deleted = deleted, viewed = viewed })
    end
    return rows
end

--- What the description pane shows follows the stream picker: a stream's summary
--- while one is selected, the PR itself on "All files".
local function render_desc()
    if not session_valid() then
        return
    end
    local width = vim.api.nvim_win_get_width(session.desc_win)
    local f = session.feature and session.guide and session.guide.features[session.feature] or nil
    if f then
        local rows = feature_rows()
        markdown.apply(
            session.desc_buf,
            markdown.render_feature(f, rows and rows[session.feature] or nil, width)
        )
    else
        markdown.apply(session.desc_buf, markdown.render_pr(session.pr, session.branch, width))
    end
end

local function redraw_tree()
    if not session_valid() then
        return
    end
    local current = session.entries[session.index]
    session.line_map = tree.render(session.tree_buf, {
        entries = session.entries,
        store = session.store,
        current_path = current and current.path or nil,
        folded = session.folded,
        header = session.base_ref,
        width = session.cfg.tree_width,
        features = feature_rows(),
        selected_feature = session.feature,
    })
    -- Park the tree cursor on the current file so the highlight and the cursor
    -- agree with each other.
    for line, item in pairs(session.line_map) do
        if item.kind == "file" and current and item.entry.path == current.path then
            if vim.api.nvim_win_is_valid(session.tree_win) then
                pcall(vim.api.nvim_win_set_cursor, session.tree_win, { line, 0 })
            end
            break
        end
    end
end

local function goto_index(idx, focus_working)
    if not session_valid() or #session.entries == 0 then
        return
    end
    idx = math.max(1, math.min(idx, #session.entries))
    session.index = idx
    layout.show_file(session, session.entries[idx])
    redraw_tree()
    ruler.update(session)
    -- After show_file, which is what computes session.hunks — the explanation
    -- blocks are keyed to them.
    explain.refresh(session)
    if focus_working ~= false and vim.api.nvim_win_is_valid(session.working_win) then
        vim.api.nvim_set_current_win(session.working_win)
    end
end

M._goto_index = goto_index

--- Select a stream from the guide (nil for "All files"): the tree, paging and
--- the viewed-advance all narrow to its files, and the description pane swaps to
--- its summary. The entry tables are shared with `all_entries`, so counts and
--- viewed marks stay one set of state however the list is filtered.
--- @param idx number|nil index into session.guide.features
--- @param opts table|nil `focus` hands focus to the working pane afterwards
local function select_feature(idx, opts)
    if not session_valid() then
        return
    end
    local entries = session.all_entries
    if idx then
        local f = session.guide and session.guide.features[idx]
        if not f then
            return
        end
        local want = {}
        for _, p in ipairs(f.files or {}) do
            want[p] = true
        end
        entries = vim.tbl_filter(function(e)
            return want[e.path]
        end, session.all_entries)
        if #entries == 0 then
            notify("no changed files matched this stream")
            return
        end
    end

    session.feature = idx
    local current = session.entries[session.index]
    session.entries = entries
    local target = 1
    for i, e in ipairs(entries) do
        if current and e.path == current.path then
            target = i
            break
        end
    end
    render_desc()
    goto_index(target, opts and opts.focus or false)
end

M._select_feature = select_feature

--- Exposed for tests and for poking at a live session from :lua.
function M._session()
    return session
end

local function step(delta)
    if not session_valid() then
        return
    end
    local n = #session.entries
    if n == 0 then
        return
    end
    -- Wrap, so mashing past the end returns to the top rather than sticking.
    local idx = ((session.index - 1 + delta) % n) + 1
    goto_index(idx)
end

--- Where to land after a file has just been ticked as viewed.
local function advance_after_view()
    if session.cfg.advance == "none" then
        return
    end
    local n = #session.entries
    if session.cfg.advance == "next_unviewed" then
        for offset = 1, n do
            local idx = ((session.index - 1 + offset) % n) + 1
            local e = session.entries[idx]
            if not session.store:is_viewed(e.path) then
                goto_index(idx)
                return
            end
        end
        notify("all files viewed")
        return
    end
    -- "next": step forward, but step over generated files, which are pre-ticked
    -- and would otherwise be un-ticked by the next press.
    for offset = 1, n do
        local idx = ((session.index - 1 + offset) % n) + 1
        local e = session.entries[idx]
        if not (e.generated and session.cfg.generated == "skip") then
            goto_index(idx)
            return
        end
    end
end

--- Toggle the current file's viewed mark. Moving on is conditional on the
--- direction of the toggle: ticking a file advances, un-ticking leaves you on it
--- so you can read it again.
local function toggle_viewed()
    if not session_valid() then
        return
    end
    local entry = session.entries[session.index]
    if not entry then
        return
    end
    local now_viewed = session.store:toggle(entry.path)
    session.store:save(session.merge_base)
    if now_viewed then
        advance_after_view()
    else
        redraw_tree()
        layout.show_file(session, entry)
    end
end

M._toggle_viewed = toggle_viewed

--- Show or hide the explanation column. Opening it populates the current file
--- immediately; the working pane gives up the columns, so the ruler floating over
--- it has to be re-laid-out either way.
local function toggle_explain(force)
    if not session_valid() then
        return
    end
    if explain.is_open(session) then
        explain.close(session)
        ruler.update(session)
        return
    end
    if not explain.open(session) then
        return
    end
    apply_keys(session.explain_buf, false)
    ruler.update(session)
    explain.refresh(session, { force = force })
end

M._toggle_explain = toggle_explain

local function tree_cursor_item()
    if not session_valid() then
        return nil
    end
    local line = vim.api.nvim_win_get_cursor(session.tree_win)[1]
    return session.line_map and session.line_map[line] or nil
end

local function tree_open()
    local item = tree_cursor_item()
    if not item then
        return
    end
    if item.kind == "feature" then
        -- The redraw parks the tree cursor on the current file; put it back on
        -- the picker so streams can be flicked through without re-climbing.
        local line = vim.api.nvim_win_get_cursor(session.tree_win)[1]
        select_feature(item.index ~= 0 and item.index or nil)
        if session_valid() and vim.api.nvim_win_is_valid(session.tree_win) then
            pcall(vim.api.nvim_win_set_cursor, session.tree_win, { line, 0 })
        end
        return
    end
    if item.kind == "dir" then
        session.folded[item.path] = not session.folded[item.path]
        redraw_tree()
        return
    end
    for i, e in ipairs(session.entries) do
        if e.path == item.entry.path then
            goto_index(i)
            return
        end
    end
end

local function tree_toggle_viewed()
    local item = tree_cursor_item()
    if not item or item.kind ~= "file" then
        return
    end
    for i, e in ipairs(session.entries) do
        if e.path == item.entry.path then
            session.index = i
            break
        end
    end
    toggle_viewed()
end

local function close_session(force)
    if not session_valid() then
        session = nil
        return
    end
    -- Don't discard unsaved edits made in the right-hand pane.
    if not force then
        for _, buf in ipairs(vim.api.nvim_list_bufs()) do
            if vim.api.nvim_buf_is_loaded(buf) and vim.bo[buf].modified and vim.bo[buf].buftype == "" then
                local name = vim.api.nvim_buf_get_name(buf)
                local answer = vim.fn.confirm("Unsaved changes in " .. vim.fn.fnamemodify(name, ":t"), "&Save\n&Discard\n&Cancel", 3)
                if answer == 1 then
                    vim.api.nvim_buf_call(buf, function()
                        vim.cmd("write")
                    end)
                elseif answer ~= 2 then
                    return
                end
            end
        end
    end
    session.store:save(session.merge_base)
    -- Before layout.close: a float left open when its parent tab goes can strand
    -- the window or block the tabclose.
    ruler.close(session)
    explain.close(session)
    layout.close(session)
    session = nil
end

local function map(buf, lhs, fn, desc)
    if not lhs or lhs == "" then
        return
    end
    vim.keymap.set("n", lhs, fn, { buffer = buf, nowait = true, silent = true, desc = "lgtm: " .. desc })
end

--- Session keymaps are buffer-local, so nothing leaks into the rest of nvim.
--- They are reapplied whenever a new working buffer is loaded into the pane.
function apply_keys(buf, is_tree)
    local k = session.cfg.keys
    map(buf, k.next_file, function() step(1) end, "next changed file")
    map(buf, k.prev_file, function() step(-1) end, "previous changed file")
    map(buf, k.next_file_alt, function() step(1) end, "next changed file")
    map(buf, k.prev_file_alt, function() step(-1) end, "previous changed file")
    map(buf, k.toggle_viewed, toggle_viewed, "toggle viewed")
    map(buf, k.toggle_explain, function() toggle_explain(false) end, "toggle the explanation column")
    map(buf, k.close, function() close_session(false) end, "close session")
    if is_tree then
        map(buf, k.tree_open, tree_open, "open file / fold directory")
        map(buf, k.tree_fold, tree_open, "fold directory")
        map(buf, k.tree_toggle_viewed, tree_toggle_viewed, "toggle viewed")
        map(buf, k.tree_close, function() close_session(false) end, "close session")
    end
end

--- @param opts table|nil `cwd` roots the session somewhere other than the
---        current directory, which is how the branch picker opens a session in
---        another worktree without disturbing where you are.
function M.open(base_arg, opts)
    if session_valid() then
        notify("session already open")
        vim.api.nvim_set_current_tabpage(session.tab)
        return
    end

    local cwd = (opts and opts.cwd) or vim.fn.getcwd()
    local root = git.root(cwd)
    if not root then
        notify("not inside a git repository", vim.log.levels.ERROR)
        return
    end

    local cfg = M.config
    local base_ref, source = git.resolve_base(root, {
        explicit = base_arg,
        base_branch = cfg.base_branch,
        gh_timeout = cfg.gh_timeout,
    })
    if not base_ref then
        notify("could not determine a base branch; pass one to :LgtmEdit", vim.log.levels.ERROR)
        return
    end

    local merge_base = git.merge_base(base_ref, root)
    if not merge_base then
        notify("no merge base with " .. base_ref, vim.log.levels.ERROR)
        return
    end

    local branch = git.branch(root)
    local entries = git.changed_files(merge_base, root, { include_untracked = cfg.include_untracked })
    if #entries == 0 then
        notify("no changes vs " .. base_ref)
        return
    end
    -- git's lexical path order interleaves root files between directories;
    -- stepping must follow the order the tree displays.
    entries = tree.display_order(entries)

    local store = state.open(git.common_dir(root), git.branch(root), root)
    store:prune(entries)
    if cfg.generated == "skip" then
        for _, e in ipairs(entries) do
            if e.generated and not store:is_viewed(e.path) then
                store:set_viewed(e.path, true)
            end
        end
    end

    tree.setup_highlights(cfg.diff_colors)
    layout.setup_winbar_highlights()
    ruler.setup_highlights(cfg.diff_colors)
    markdown.setup_highlights(cfg.diff_colors)
    explain.setup_highlights(cfg.diff_colors)
    local wins = layout.create(cfg)

    -- Tab-local, so a session opened in another worktree gets that directory
    -- without moving the cwd of every other tab you have open.
    pcall(vim.cmd, "tcd " .. vim.fn.fnameescape(root))

    session = vim.tbl_extend("force", wins, {
        cfg = cfg,
        root = root,
        base_ref = base_ref,
        branch = branch,
        merge_base = merge_base,
        -- `entries` is what the tree shows and paging walks; `all_entries` is the
        -- whole change, which is what the explanation run and the stream stats
        -- are always about. Same entry tables in both, so counts and viewed
        -- marks are one set of state.
        entries = entries,
        all_entries = entries,
        feature = nil,
        store = store,
        index = 1,
        folded = {},
    })

    -- A guide cached by an earlier run puts the stream picker up immediately;
    -- otherwise it appears when the explanation run writes one.
    session.guide = explain.load_guide(session)
    session.guide_json = session.guide and vim.json.encode(session.guide) or nil
    session.on_guide = function()
        if not session_valid() then
            return
        end
        if session.feature then
            -- A refined guide may have regrouped or dropped the selected stream;
            -- reselect so the filter follows it rather than going stale.
            local n = session.guide and #session.guide.features or 0
            select_feature(session.feature <= n and session.feature or nil)
        else
            redraw_tree()
        end
    end

    -- Reapply the maps each time a file is loaded into a pane, since :edit swaps
    -- the buffer out from under them.
    session.augroup = vim.api.nvim_create_augroup("lgtm_session", { clear = true })
    vim.api.nvim_create_autocmd({ "BufWinEnter" }, {
        group = session.augroup,
        callback = function(args)
            if not session_valid() then
                return
            end
            local win = vim.fn.bufwinid(args.buf)
            if win == session.working_win or win == session.base_win then
                apply_keys(args.buf, false)
            end
        end,
    })
    -- Saving a file changes its counts, so refresh that row.
    vim.api.nvim_create_autocmd("BufWritePost", {
        group = session.augroup,
        callback = function(args)
            if not session_valid() then
                return
            end
            local name = vim.api.nvim_buf_get_name(args.buf)
            local rel = name:sub(#session.root + 2)
            for _, e in ipairs(session.all_entries) do
                if e.path == rel then
                    local fresh = git.changed_files(session.merge_base, session.root, {
                        include_untracked = session.cfg.include_untracked,
                    })
                    for _, f in ipairs(fresh) do
                        if f.path == rel then
                            e.added, e.deleted, e.no_counts = f.added, f.deleted, f.no_counts
                        end
                    end
                    redraw_tree()
                    break
                end
            end
        end,
    })
    -- 'scrollbind' only syncs when the *current* window scrolls. Turning the
    -- mouse wheel over a pane that does not have focus scrolls it directly, so
    -- the two sides drift apart — which reads as the diff being scroll-locked
    -- one way but not the other. Realign from whichever pane moved.
    local syncing = false
    vim.api.nvim_create_autocmd("WinScrolled", {
        group = session.augroup,
        callback = function()
            if syncing or not session_valid() then
                return
            end
            local current = vim.api.nvim_get_current_win()
            local scrolled
            for id, delta in pairs(vim.v.event or {}) do
                local win = tonumber(id)
                if
                    win
                    and win ~= current
                    and (win == session.base_win or win == session.working_win)
                    and type(delta) == "table"
                    and (delta.topline or 0) ~= 0
                then
                    scrolled = win
                    break
                end
            end
            if not scrolled then
                return
            end
            syncing = true
            pcall(layout.sync_scroll, session, scrolled)
            syncing = false
        end,
    })

    -- The ruler's viewport marker has to follow any scroll, focused or not, and
    -- the strip has to be re-laid-out whenever the pane changes size.
    vim.api.nvim_create_autocmd({ "WinScrolled", "VimResized", "WinResized" }, {
        group = session.augroup,
        callback = function()
            if session_valid() then
                pcall(ruler.update, session)
                pcall(explain.relayout_if_stale, session)
                pcall(explain.sync, session)
            end
        end,
    })

    -- The explanation pane also follows the cursor, not only the viewport: moving
    -- between two hunks on one screen changes which block is the active one
    -- without scrolling anything.
    vim.api.nvim_create_autocmd({ "CursorMoved", "CursorHold" }, {
        group = session.augroup,
        callback = function()
            if not session_valid() then
                return
            end
            -- A fold can be opened with `zo` without scrolling anything and
            -- without moving the cursor, so CursorHold is the backstop that
            -- catches it. Both are guarded by a cheap signature.
            pcall(explain.relayout_if_stale, session)
            if vim.api.nvim_get_current_win() == session.working_win then
                pcall(explain.sync, session)
            end
        end,
    })

    vim.api.nvim_create_autocmd("TabClosed", {
        group = session.augroup,
        callback = function()
            if session and session.tab and not vim.api.nvim_tabpage_is_valid(session.tab) then
                session.store:save(session.merge_base)
                -- Closing the tab with :q never reaches layout.close, so the
                -- borrowed global options would otherwise stay changed.
                if session.saved_opts then
                    vim.o.laststatus = session.saved_opts.laststatus
                    vim.o.fillchars = session.saved_opts.fillchars
                end
                ruler.close(session)
                explain.stop_run(session)
                session = nil
            end
        end,
    })

    -- The description pane fills in when gh answers; the session is usable
    -- immediately rather than waiting on the network.
    render_desc()
    git.pr_view(nil, root, function(pr)
        if not session_valid() then
            return
        end
        -- Kept for the explanation agent, which is given the PR body as the
        -- statement of intent the diff is supposed to deliver.
        session.pr = pr
        -- Only while the pane is showing the PR: a selected stream keeps its
        -- summary rather than being interrupted by the network answering.
        if not session.feature then
            render_desc()
        end
    end)

    apply_keys(session.tree_buf, true)
    apply_keys(session.desc_buf, false)
    goto_index(1)
    notify(string.format("%d files vs %s (%s)", #entries, base_ref, source))
end

function M.close()
    close_session(false)
end

function M.setup(opts)
    M.config = vim.tbl_deep_extend("force", vim.deepcopy(defaults), opts or {})

    vim.api.nvim_create_user_command("LgtmEdit", function(args)
        M.open(args.args ~= "" and args.args or nil)
    end, {
        nargs = "?",
        desc = "Review this branch's PR diff",
        complete = function(lead)
            local out = vim.fn.systemlist("git for-each-ref --format='%(refname:short)' refs/heads refs/remotes")
            return vim.tbl_filter(function(ref)
                return ref:find(lead, 1, true) == 1
            end, out)
        end,
    })

    vim.api.nvim_create_user_command("LgtmClose", function()
        close_session(false)
    end, { desc = "Close the lgtm session" })

    vim.api.nvim_create_user_command("LgtmExplain", function(args)
        if not session then
            vim.notify("lgtm: no session open", vim.log.levels.WARN)
            return
        end
        -- With a bang on an already-open pane, regenerate rather than close: that
        -- is the only way past a cached answer, and closing it is what the toggle
        -- key is for.
        if args.bang and explain.is_open(session) then
            explain.refresh(session, { force = true })
            return
        end
        toggle_explain(args.bang)
    end, { bang = true, desc = "Toggle the explanation column (! regenerates)" })

    vim.api.nvim_create_user_command("LgtmExplainClearCache", function()
        if not session then
            vim.notify("lgtm: no session open", vim.log.levels.WARN)
            return
        end
        vim.notify(string.format("lgtm: dropped %d file(s) from this branch's store", explain.clear_store(session)))
    end, { desc = "Drop this branch's stored explanations" })

    vim.api.nvim_create_user_command("LgtmPick", function()
        require("lgtm.picker").open({ base_branch = M.config.base_branch })
    end, { desc = "Pick a branch to review" })
end

return M
